New AppCatalog CRD
giantswarm/apiextensions pull request #178
Opened 2018-12-05 17:00 UTC by tomahawk28

2018-12-05 18:05 UTC, rossf7 requested changes
Direction is good but the naming is very important because of the code generation. So some renaming is needed. Let me know if any of this doesn't make sense.

2018-12-05 18:05 UTC, rossf7 commented on pkg/apis/core/v1alpha1/app_catalog_types.go
> +type AppCatalogConfigSpecAppCatalog struct {
This should just be `AppCatalogSpec`.

2018-12-05 18:05 UTC, rossf7 commented on pkg/apis/core/v1alpha1/app_catalog_types.go
> +type AppCatalogStorage struct {
The naming of the structs is a bit weird but its required by the code generation. So this should be `AppCatalogSpecCatalogStorage`.

2018-12-06 09:44 UTC, puja108 commented on pkg/apis/core/v1alpha1/app_catalog_types.go
> +type AppCatalogConfig struct {
@tomahawk28 you changed it here in line 50 but we need to remove the `config` part from everywhere in this PR, it should always be `AppCatalog..` without config, otherwise we will have issues with the naming here

2018-12-06 09:46 UTC, puja108 commented on pkg/apis/core/v1alpha1/app_catalog_types.go
> +//       name: appcatalogconfigs.core.giantswarm.io
```suggestion
//       name: appcatalogconfigs.app.giantswarm.io
```

2018-12-06 09:46 UTC, puja108 commented on pkg/apis/core/v1alpha1/app_catalog_types.go
> +//       group: core.giantswarm.io
```suggestion
//       group: app.giantswarm.io
```

2018-12-06 09:47 UTC, puja108 commented on pkg/apis/core/v1alpha1/app_catalog_types.go
> +//         singular: appcatalogconfig
remove `config` from the above 3 lines

2018-12-06 09:47 UTC, puja108 commented on pkg/apis/core/v1alpha1/app_catalog_types.go
> +//       scope: Namespaced
```suggestion
//       scope: Cluster
```

2018-12-06 09:48 UTC, puja108 commented on pkg/apis/core/v1alpha1/app_catalog_types.go
> +func NewAppCatalogConfigCRD() *apiextensionsv1beta1.CustomResourceDefinition {
```suggestion
func NewAppCatalogCRD() *apiextensionsv1beta1.CustomResourceDefinition {
```

2018-12-06 09:48 UTC, puja108 commented on pkg/apis/core/v1alpha1/app_catalog_types.go
> +			Name: "appcatalogconfigs.core.giantswarm.io",
```suggestion
			Name: "appcatalogs.app.giantswarm.io",
```

2018-12-06 09:48 UTC, puja108 commented on pkg/apis/core/v1alpha1/app_catalog_types.go
> +			Group:   "core.giantswarm.io",
```suggestion
			Group:   "app.giantswarm.io",
```

2018-12-06 09:48 UTC, puja108 commented on pkg/apis/core/v1alpha1/app_catalog_types.go
> +				Singular: "appcatalogconfig",
agai remove config above 3 lines

2018-12-06 09:49 UTC, puja108 commented on pkg/apis/core/v1alpha1/app_catalog_types.go
> +	Spec              AppCatalogConfigSpec `json:"spec"`
```suggestion
	Spec              AppCatalogSpec `json:"spec"`
```

2018-12-06 09:49 UTC, puja108 commented on pkg/apis/core/v1alpha1/app_catalog_types.go
> +	Status            ChartConfigStatus    `json:"status"`
```suggestion
	Status            AppCatalogStatus    `json:"status"`
```

2018-12-06 09:50 UTC, puja108 commented on pkg/apis/core/v1alpha1/app_catalog_types.go
> +	VersionBundle AppCatalogConfigSpecVersionBundle `json:"versionBundle" yaml:"versionBundle"`
not sure we need version bundle here still @rossf7 	?

2018-12-06 09:50 UTC, puja108 commented on pkg/apis/core/v1alpha1/app_catalog_types.go
> +type AppCatalogConfigSpec struct {
```suggestion
type AppCatalogSpec struct {
```

2018-12-06 09:52 UTC, puja108 commented on pkg/apis/core/v1alpha1/app_catalog_types.go
> +	// e.g. kube-system.
```suggestion
	// e.g. https://giantswarm.github.com/app-catalog/.
```

2018-12-06 09:52 UTC, puja108 commented on pkg/apis/core/v1alpha1/app_catalog_types.go
> +	// Type indicates which package type would use for this AppCatalog
```suggestion
	// Type indicates which repository type would be use for this AppCatalog
```

2018-12-06 09:53 UTC, puja108 commented on pkg/apis/core/v1alpha1/app_catalog_types.go
> +	// URL is the link where this AppCatalog's package file have been located
```suggestion
	// URL is the link to where this AppCatalog's repository is located
```

2018-12-06 09:54 UTC, puja108 commented on pkg/apis/core/v1alpha1/app_catalog_types.go
> +}
might wanna remove the above 3 lines if we do not need versionbundle here

2018-12-06 09:55 UTC, puja108 commented on pkg/clientset/versioned/typed/core/v1alpha1/appcatalog.go
> +		Namespace(c.ns).
the CRD is not namespaced so there won't be a ns

2018-12-06 09:55 UTC, puja108 commented on pkg/clientset/versioned/typed/core/v1alpha1/appcatalog.go
> +		Namespace(c.ns).
again no namespace

2018-12-06 09:56 UTC, puja108 commented on pkg/clientset/versioned/typed/core/v1alpha1/appcatalog.go
> +		Namespace(c.ns).
s.a.

2018-12-06 09:56 UTC, puja108 commented on pkg/clientset/versioned/typed/core/v1alpha1/appcatalog.go
> +		Namespace(c.ns).
s.a.

2018-12-06 09:56 UTC, puja108 commented on pkg/clientset/versioned/typed/core/v1alpha1/appcatalog.go
> +		Namespace(c.ns).
s.a.

2018-12-06 09:56 UTC, puja108 commented on pkg/clientset/versioned/typed/core/v1alpha1/appcatalog.go
> +		Namespace(c.ns).
s.a.

2018-12-06 09:56 UTC, puja108 commented on pkg/clientset/versioned/typed/core/v1alpha1/appcatalog.go
> +		Namespace(c.ns).
s.a.

2018-12-06 09:56 UTC, puja108 commented on pkg/clientset/versioned/typed/core/v1alpha1/appcatalog.go
> +		Namespace(c.ns).
s.a.

2018-12-06 09:56 UTC, puja108 commented on pkg/clientset/versioned/typed/core/v1alpha1/appcatalog.go
> +		Namespace(c.ns).
s.a.

2018-12-06 09:58 UTC, puja108 commented on pkg/clientset/versioned/typed/core/v1alpha1/appcatalogconfig.go
> +/*
i think this file is remaining duplicate of above file

2018-12-06 09:58 UTC, puja108 commented on pkg/clientset/versioned/typed/core/v1alpha1/fake/fake_appcatalog.go
> +var appcatalogsResource = schema.GroupVersionResource{Group: "core.giantswarm.io", Version: "v1alpha1", Resource: "appcatalogs"}
```suggestion
var appcatalogsResource = schema.GroupVersionResource{Group: "app.giantswarm.io", Version: "v1alpha1", Resource: "appcatalogs"}
```

2018-12-06 09:59 UTC, puja108 commented on pkg/clientset/versioned/typed/core/v1alpha1/fake/fake_appcatalog.go
> +var appcatalogsKind = schema.GroupVersionKind{Group: "core.giantswarm.io", Version: "v1alpha1", Kind: "AppCatalog"}
```suggestion
var appcatalogsKind = schema.GroupVersionKind{Group: "app.giantswarm.io", Version: "v1alpha1", Kind: "AppCatalog"}
```

2018-12-06 09:59 UTC, puja108 commented on pkg/clientset/versioned/typed/core/v1alpha1/fake/fake_appcatalog.go
> +		Invokes(testing.NewGetAction(appcatalogsResource, c.ns, name), &v1alpha1.AppCatalog{})
there's no ns

2018-12-06 09:59 UTC, puja108 commented on pkg/clientset/versioned/typed/core/v1alpha1/fake/fake_appcatalog.go
> +		Invokes(testing.NewListAction(appcatalogsResource, appcatalogsKind, c.ns, opts), &v1alpha1.AppCatalogList{})
no ns

2018-12-06 09:59 UTC, puja108 commented on pkg/clientset/versioned/typed/core/v1alpha1/fake/fake_appcatalog.go
> +		InvokesWatch(testing.NewWatchAction(appcatalogsResource, c.ns, opts))
s.a.

2018-12-06 09:59 UTC, puja108 commented on pkg/clientset/versioned/typed/core/v1alpha1/fake/fake_appcatalog.go
> +		Invokes(testing.NewCreateAction(appcatalogsResource, c.ns, appCatalog), &v1alpha1.AppCatalog{})
s.a.

2018-12-06 10:00 UTC, puja108 commented on pkg/clientset/versioned/typed/core/v1alpha1/fake/fake_appcatalog.go
> +		Invokes(testing.NewUpdateAction(appcatalogsResource, c.ns, appCatalog), &v1alpha1.AppCatalog{})
s.a.

2018-12-06 10:00 UTC, tomahawk28 commented
@puja108 the `/versioned`.. part is auto-generated, you don't need to check the part of it.

2018-12-06 10:00 UTC, puja108 commented on pkg/clientset/versioned/typed/core/v1alpha1/fake/fake_appcatalog.go
> +		Invokes(testing.NewUpdateSubresourceAction(appcatalogsResource, "status", c.ns, appCatalog), &v1alpha1.AppCatalog{})
s.a.

2018-12-06 10:00 UTC, puja108 commented on pkg/clientset/versioned/typed/core/v1alpha1/fake/fake_appcatalog.go
> +		Invokes(testing.NewDeleteAction(appcatalogsResource, c.ns, name), &v1alpha1.AppCatalog{})
s.a.

2018-12-06 10:00 UTC, puja108 commented on pkg/clientset/versioned/typed/core/v1alpha1/fake/fake_appcatalog.go
> +	action := testing.NewDeleteCollectionAction(appcatalogsResource, c.ns, listOptions)
s.a.

2018-12-06 10:00 UTC, puja108 commented on pkg/clientset/versioned/typed/core/v1alpha1/fake/fake_appcatalog.go
> +		Invokes(testing.NewPatchSubresourceAction(appcatalogsResource, c.ns, name, data, subresources...), &v1alpha1.AppCatalog{})
s.a.

2018-12-06 10:01 UTC, puja108 commented on pkg/clientset/versioned/typed/core/v1alpha1/fake/fake_appcatalogconfig.go
> +/*
again duplicate with config in the name

2018-12-06 10:01 UTC, puja108 commented on pkg/clientset/versioned/typed/core/v1alpha1/fake/fake_core_client.go
> +	return &FakeAppCatalogs{c, namespace}
no ns

2018-12-06 10:03 UTC, puja108 reviewed
minor things only:
- some remainders of `config`
- no namespace in a cluster scoped object
- group should be app. no core.

2018-12-06 10:03 UTC, puja108 commented
@giantswarm/team-batman any other fields we might need and have forgotten in our spec? especially @oponder @indyfree

2018-12-06 10:35 UTC, tomahawk28 commented on pkg/apis/core/v1alpha1/app_catalog_types.go
> +}
Not sure why, but any other CRD has this information, probably some interface are expected this one

2018-12-06 10:44 UTC, tomahawk28 commented on pkg/clientset/versioned/typed/core/v1alpha1/appcatalog.go
> +		Namespace(c.ns).
I'm not sure how I can change the auto-generated code part but this `c.ns` would be definitely `Cluster` value, isn't it?

2018-12-06 10:59 UTC, rossf7 commented on pkg/apis/core/v1alpha1/app_catalog_types.go
> +	VersionBundle AppCatalogConfigSpecVersionBundle `json:"versionBundle" yaml:"versionBundle"`
AIUI the appcatalog CRD will be a reference CRD without an operator watching it. Is that correct? 

If so it can be removed. For the other CRDs that are watched by operators we will need it. But I think we should move it to `ObjectMeta`.

See my comment on the spec. https://github.com/giantswarm/giantswarm/pull/4577#pullrequestreview-181818302

2018-12-06 11:06 UTC, tomahawk28 commented
@rossf7 Regarding namespace part in auto-generated code, I'm not sure we should change that. since it would be created every time we run `./script/gen.sh`

2018-12-06 11:12 UTC, rossf7 reviewed
This is getting there a couple more changes are needed.

@puja108 On moving version bundle to the CR metadata. I think this is required but I'll talk with the rest of sig-operator tomorrow.

2018-12-06 11:12 UTC, rossf7 commented on pkg/apis/core/v1alpha1/app_catalog_types.go
> +	AppCatalog    AppCatalogResource                `json:"appCatalog" yaml:"appCatalog"`
This `AppCatalogResource` struct shouldn't be there. As per the spec all the fields except `catalogStorage` should be part of `AppCatalogSpec`.

```
    spec:
      title: “Giant Swarm”
      description: “Catalog of Apps by Giant Swarm”
      catalogStorage:
        type: "helm"
        URL: “https://giantswarm.github.com/app-catalog/”
      logoURL: “https://s.giantswarm.io/...”
```

2018-12-06 11:12 UTC, rossf7 commented on pkg/apis/core/v1alpha1/app_catalog_types.go
> +	ReleaseStatus string `json:"releaseStatus" yaml:"releaseStatus"`
Looks like this is copy paste from the chartconfig CRD? 

Not sure if we need a status struct for the `appCatalog`. It isn't in the spec so lets remove for now.

2018-12-06 11:15 UTC, rossf7 commented on pkg/clientset/versioned/typed/core/v1alpha1/appcatalog.go
> +		Namespace(c.ns).
Yes we need to be careful as we can't change any of the autogenerated code.

The process needs to be to change the editable part and then rerun the gen.sh script.

2018-12-06 11:20 UTC, rossf7 commented on pkg/clientset/versioned/typed/core/v1alpha1/appcatalog.go
> +		Namespace(c.ns).
Looked into this a bit more and yes the value just needs to be `Cluster` in the definition. So we can ignore these namespaces in the autogen code.

https://github.com/giantswarm/apiextensions/blob/f55835d4097256c652f2b8b95b485be6aaa4611a/pkg/apis/core/v1alpha1/app_catalog_types.go#L36

2018-12-06 11:29 UTC, TheoBrigitte requested changes
Some changes required in comments

2018-12-06 11:37 UTC, puja108 commented on pkg/apis/core/v1alpha1/app_catalog_types.go
> +	ReleaseStatus string `json:"releaseStatus" yaml:"releaseStatus"`
yeah, not sure we need it, yet, we might be able to communicate back things like `lastSync` or `lastSeen` or sth if we do some caching of the catalog index in the operator.

2018-12-06 11:38 UTC, puja108 commented on pkg/apis/core/v1alpha1/app_catalog_types.go
> +// NewAppCatalogConfigCRD returns a new custom resource definition for AppCatalogConfig.
IIRC we decided to have an example here always, to make review and discussion about the resource itself easier and not having dispersed over the code below

2018-12-06 11:44 UTC, rossf7 commented on pkg/apis/core/v1alpha1/app_catalog_types.go
> +	ReleaseStatus string `json:"releaseStatus" yaml:"releaseStatus"`
Yes we'll definitely need a status struct for `appDeployment` not sure yet about `appCatalog`. I'd say leave it for now but keep it in mind during dev.

2018-12-06 13:21 UTC, tomahawk28 commented on pkg/apis/core/v1alpha1/app_catalog_types.go
> +	ReleaseStatus string `json:"releaseStatus" yaml:"releaseStatus"`
I'll delete it for now :)

2018-12-06 14:38 UTC, puja108 commented on pkg/apis/core/v1alpha1/app_catalog_types.go
> +}
yes I know, we need to check with SIG operator if we need it and if we want to tie in so closely to the general versioning of GS components. it makes our components very opinionated and not nicely portable to other environments

2018-12-07 09:12 UTC, rossf7 reviewed
This is getting there but before it can be merged the `app` group needs to be created and the code moved. See my comment for the docs for that.

2018-12-07 09:12 UTC, rossf7 commented on pkg/apis/core/v1alpha1/app_catalog_types.go
> +// NewAppCatalogCRD returns a new custom resource definition for AppCatalogConfig.
Comment still has Config in the name.

2018-12-07 09:12 UTC, rossf7 commented on pkg/apis/core/v1alpha1/app_catalog_types.go
> +//       group: app.giantswarm.io
This first PR is in the `core` group to keep things simple. But you'll need to follow these steps to create the new app group. https://github.com/giantswarm/apiextensions/#adding-a-new-group-andor-version

This will create a new dir `/pkg/apis/app/v1alpha1`.

2018-12-07 10:09 UTC, rossf7 reviewed
@tomahawk28 Thanks for moving to the `app` group.

Just a nitpick on the comments but otherwise looking good. I think this is ready for a wider review from sig-operator.

Could you remove the WIP prefix and add a description to the PR. Its a good idea to link to the issue and in this case also to the spec PR.

2018-12-07 10:09 UTC, rossf7 commented on pkg/apis/app/v1alpha1/app_catalog_types.go
> +	// Type indicates which repository type would be used for this AppCatalog
Very nitpicky now but these are godoc comments so they should be sentences and end with a `.`.

2018-12-07 10:16 UTC, tomahawk28 commented
Spec PR is linked to issue as well, I think we can keep issue link only.

2018-12-07 10:33 UTC, MarcelMue approved these changes
LGTM overall, make Ross happy and I am happy.

2018-12-07 10:33 UTC, MarcelMue commented on pkg/apis/app/v1alpha1/app_catalog_types.go
> +	Type string `json:"type" yaml:"type"`
I don't love this because this will mean that we have to compare strings to figure out which type out struct is. I am not sure if it's possible to have an interface here and then have different structs for `helm` and so on. Then we could assert against the struct type.

Not a big deal though, as I am not sure how easy that is.

2018-12-07 11:10 UTC, rossf7 approved these changes
LGTM once godoc nitpick is addressed.

2018-12-07 11:10 UTC, rossf7 commented on pkg/apis/app/v1alpha1/app_catalog_types.go
> +	Type string `json:"type" yaml:"type"`
Good point but I'm also not sure if we can have interfaces here. As k8s needs to serialize and deserialize.

The magic strings for the types is a pain because they'll be needed in multiple components. IMO we'll need a library for this.

2018-12-07 16:06 UTC, tomahawk28 commented
@TheoBrigitte Let me know if it's good to go :)

2018-12-10 13:27 UTC, TheoBrigitte approved these changes
LGTM

2018-12-10 13:31 UTC, merged