WIP: Catalog app deployment
giantswarm/apiextensions pull request #179
Opened 2018-12-10 14:50 UTC by tomahawk28

Still, need to improve code comments.

2018-12-10 14:59 UTC, tomahawk28 commented on pkg/apis/app/v1alpha1/app_deployment_types.go
> +	App     string `json:"app" yaml:"app"`
It's not clear to me what is the actual difference between catalog and app in here. Any suggestion?

2018-12-10 15:00 UTC, tomahawk28 commented on pkg/apis/app/v1alpha1/app_deployment_types.go
> +	Namespace string                  `json:"namespace" yaml:"namespace"`
If `kubeContext` is here, do we really need `namespace`? I looked upon the relevant document and it saying that `namespace` is part of kube context. https://kubernetes.io/docs/tasks/access-application-cluster/configure-access-multiple-clusters/#define-clusters-users-and-contexts

2018-12-10 16:15 UTC, rossf7 reviewed
Direction is good. Godoc needs updated and answered your questions.

An admin point. We don't use the `help-wanted` label internally. You can ask for help in any PR! Just ping the relevant people or teams in the PR.

2018-12-10 16:15 UTC, rossf7 commented on pkg/apis/app/v1alpha1/app_deployment_types.go
> +//       scope: Cluster
This should also be `Namespaced`.

2018-12-10 16:15 UTC, rossf7 commented on pkg/apis/app/v1alpha1/app_deployment_types.go
> +//         singular: appdeployments
This should also be `appdeployment`.

2018-12-10 16:15 UTC, rossf7 commented on pkg/apis/app/v1alpha1/app_deployment_types.go
> +	App     string `json:"app" yaml:"app"`
Lets use `prometheus` here as this is the first app we will be making available.

2018-12-10 16:15 UTC, rossf7 commented on pkg/apis/app/v1alpha1/app_deployment_types.go
> +	Namespace string                  `json:"namespace" yaml:"namespace"`
Yes they are separate. The `kubeContext` will have the namespace where the operator should connect to deploy the app, e.g `giantswarm` to connect to our Tiller pod.

This namespace is where the app should be deployed, e.g `giantswarm-prometheus`.

2018-12-10 17:30 UTC, rossf7 reviewed
Direction is good here. Lets get the examples sorted and then it can be submitted for review.

2018-12-10 17:30 UTC, rossf7 commented on pkg/apis/app/v1alpha1/app_deployment_types.go
> +	App     string `json:"app" yaml:"app"`
We need godoc and examples for each field. The examples are to make the CRD easier to read.

Lets align with the example in the spec PR.

```
spec:
  catalog: "giant-swarm"
  app: “kubernetes-prometheus”
  release: 1.0.0
  kubeContext: “giantswarm-12345”
  namespace: “monitoring”
```

2018-12-11 09:41 UTC, xh3b4sd commented
FYI the `apiextensions` are more and more becoming a directly user facing API. So @giantswarm/sig-ux is a little bit concerned with that. Let's always request their feedback on PRs like this here. To make it easier to reason about the implications and how it looks like we would like to have an example YAML of the added CRs in the godoc. Can you please add these? That would be super cool.

2018-12-11 09:46 UTC, xh3b4sd submitted a review, later dismissed
Note that in some places we started to add another helper function for the type meta. When you think this is useful you can also add it. See https://github.com/giantswarm/apiextensions/blob/858ead97a5762244870ebbe3a83503f5132b2fde/pkg/apis/core/v1alpha1/drainer_types.go#L67-L72 for instance.

2018-12-11 09:46 UTC, xh3b4sd commented on pkg/apis/app/v1alpha1/app_deployment_types.go
> +		Spec: apiextensionsv1beta1.CustomResourceDefinitionSpec{
Can you please add the status subresources to the CRD? We should always add these by default to all new types.

2018-12-11 10:00 UTC, rossf7 requested changes
Godoc isn't accurate in some places. I included some suggested text. Also like Tim says we need the status subresource.

2018-12-11 12:18 UTC, rossf7 reviewed
@tomahawk28 This is looking good but it still needs the godoc example of how the CR will look. You can base that on examples in the spec PR. Please also add an example for the appCatalog CR.

```
spec:
  catalog: "giant-swarm"
  app: “kubernetes-prometheus”
  release: 1.0.0
  kubeContext: “giantswarm-12345”
  namespace: “monitoring”
```

2018-12-11 12:52 UTC, kopiczko requested changes

2018-12-11 12:52 UTC, kopiczko commented on pkg/apis/app/v1alpha1/app_catalog_types.go
> +//         URL: "https://giantswarm.github.com/app-catalog/"
```suggestion
//         URL: "https://github.com/giantswarm/app-catalog/"
```

2018-12-11 12:52 UTC, kopiczko commented on pkg/apis/app/v1alpha1/app_catalog_types.go
> +//       description: “Catalog of Apps by Giant Swarm"
```suggestion
//       description: “Catalog of Apps by Giant Swarm."
```

2018-12-11 12:52 UTC, kopiczko commented on pkg/apis/app/v1alpha1/app_deployment_types.go
> +// Example of AppDeployment CR as below.
To make it a valid godoc:

```suggestion
// AppDeployment CR example as below.
```

2018-12-11 12:52 UTC, kopiczko commented on pkg/apis/app/v1alpha1/app_catalog_types.go
> +// Example of AppCatalog CR as below.
To make it a valid godoc:

```suggestion
// AppCatalog CR example as below.
```

2018-12-11 12:52 UTC, kopiczko commented on pkg/apis/app/v1alpha1/app_deployment_types.go
> +	Namespace string                  `json:"namespace" yaml:"namespace"`
`kubeContext` is a terrible name IMO. When I read that it feels like `kubectl` context. Is is something from upstream?

@rossf7 you say

> The kubeContext will have the namespace where the operator should connect to deploy the app

Then I see:

```
	// Namespace is the namespace where the app should be deployed.
	// e.g. monitoring
	Namespace string   
```

We need to make this straight from the beggining IMO.

I understand this is just a `tillerNamespace` but we don't want to call it tiller as we want to get rid of it. What will it be replaced with then? How to call that?

2018-12-11 12:53 UTC, tomahawk28 commented on pkg/apis/app/v1alpha1/app_catalog_types.go
> +//         URL: "https://giantswarm.github.com/app-catalog/"
Ah, How I pass this 🤦‍♂️ Thanks

2018-12-11 13:17 UTC, tomahawk28 commented
@kopiczko From what I understand, `kubeContext` is one of the `context` from the control plane, not the namespace. is it correct? @rossf7

2018-12-11 14:24 UTC, rossf7 commented on pkg/apis/app/v1alpha1/app_deployment_types.go
> +	Namespace string                  `json:"namespace" yaml:"namespace"`
Damnit sry my comment didn't help here :( I'm not feeling well didn't get much sleep.

kubeContext is the name of the cluster to connect to. My understanding is this part of the UX changes. As it matches the kube context the user will have created with gsctl. However the design was done while I was away.

@kopiczko I think it makes more sense to address this in the spec PR. Please leave your feedback there if you have concerns.
https://github.com/giantswarm/giantswarm/pull/4577

On the namespace point I don't follow. Its the namespace where the app should be deployed. It isn't the namespace where tiller is installed.

2018-12-12 07:55 UTC, kopiczko commented on pkg/apis/app/v1alpha1/app_deployment_types.go
> +	Namespace string                  `json:"namespace" yaml:"namespace"`
Thanks for pointing me to the spec. I already left a comment there.

Re namespace: I didn't mean `namespace` -> `tillerNamespace` but `kubeContext` -> `tillerNamespace`.

2018-12-18 10:37 UTC, puja108 commented
we need to sync this with the spec again

2018-12-18 13:20 UTC, tomahawk28 commented
@puja108 I'm still waiting for the spec is merged, will do that soon after that.

2018-12-18 13:58 UTC, rossf7 reviewed
> should we move this chart CRD to application group?

Yes we want all 3 CRDs to use the new group. Can you update this PR so it matches the spec?

I hope we'll get the spec merged today by updating this PR we can prepare for that.

https://github.com/giantswarm/giantswarm/pull/4577#discussion_r242537961

2018-12-18 16:15 UTC, tomahawk28 commented
@giantswarm/team-batman @giantswarm/sig-operator I updated as an agreement that we had, let's merge this asap :)

2018-12-18 16:50 UTC, kopiczko commented on pkg/apis/application/v1alpha1/app_catalog_types.go
> +//         URL: "https://github.com/giantswarm/app-catalog/"
Apparently previous version was correct. It is a github page.

```suggestion
//         URL: "https://giantswarm.github.com/app-catalog/"
```

2018-12-18 16:50 UTC, kopiczko commented on pkg/apis/application/v1alpha1/app_types.go
> +//		    namespace: "12345"
Indentation is broken here.

2018-12-18 16:50 UTC, kopiczko commented on pkg/apis/application/v1alpha1/app_types.go
> +//       name: “My-Cool-Prometheus”
```suggestion
//       name: "My-Cool-Prometheus"
```

2018-12-18 16:50 UTC, kopiczko commented on pkg/apis/application/v1alpha1/app_types.go
> +//       name: “My-Cool-Prometheus”
Those quotes `”` appear in many places. Please fix them.

2018-12-18 16:50 UTC, kopiczko commented on pkg/apis/application/v1alpha1/app_types.go
> +//       releaseStatus: “DEPLOYED”
I can easily see we add more fields to the release here. I would prefer to have one level more here like below. This also would mean structs changes.

```
//       release:
//         status: “DEPLOYED”
```

2018-12-18 16:50 UTC, kopiczko commented on pkg/apis/application/v1alpha1/app_types.go
> +//       app: “kubernetes-prometheus”
I think `name` is better fit than `app` here as this is `App` kind.

2018-12-18 17:00 UTC, tomahawk28 commented on pkg/apis/application/v1alpha1/app_types.go
> +//       app: “kubernetes-prometheus”
@kopiczko Can you please write that requests on spec review, We need to sync on that PR, especially about spec things at there.

2018-12-18 17:02 UTC, tomahawk28 commented on pkg/apis/application/v1alpha1/app_types.go
> +//       releaseStatus: “DEPLOYED”
@kopiczko this as well

2018-12-18 17:07 UTC, rossf7 commented
@kopiczko Yes it will be easier to add further feedback to the spec PR. But I like both these suggestions. I'll update the spec PR because I need to merge it soon.

2018-12-19 06:56 UTC, rossf7 reviewed
Some more changes needed.

2018-12-19 06:56 UTC, rossf7 commented on pkg/apis/application/v1alpha1/app_types.go
> +	Spec              AppSpec `json:"spec"`
Status struct is missing here.

2018-12-19 06:56 UTC, rossf7 commented on pkg/apis/application/v1alpha1/app_types.go
> +	Status     AppSpecStatus     `json:"status" yaml:"status"`
Status should move to the line above.

2018-12-19 06:56 UTC, rossf7 commented on pkg/apis/application/v1alpha1/app_types.go
> +	Secret AppSpecSecret `json:"secret" yaml:"secret"`
I think this should be `AppSpecKubeConfigSecret`.

2018-12-19 06:56 UTC, rossf7 commented on pkg/apis/application/v1alpha1/app_types.go
> +type AppSpecSecret struct {
Same here. Should be `AppSpecKubeConfigSecret`.

2018-12-19 06:56 UTC, rossf7 commented on pkg/apis/application/v1alpha1/app_types.go
> +type AppSpecStatus struct {
Should just be `AppStatus`.

2018-12-19 06:56 UTC, rossf7 commented on pkg/apis/application/v1alpha1/app_types.go
> +type AppSpecStatusRelease struct {
This struct is no longer needed.

2018-12-19 13:56 UTC, rossf7 reviewed
Next round of feedback.

In the comments a lot of references to app are now application. Is that intentional? I found it easier to read before since the CRDs are app and appCatalog.

2018-12-19 13:56 UTC, rossf7 commented on pkg/apis/application/v1alpha1/app_types.go
> +	Secret AppSpecKubeConfigSecret `json:"secret" yaml:"secret"`
These fields should have godoc comments.

2018-12-19 13:56 UTC, rossf7 commented on pkg/apis/application/v1alpha1/app_types.go
> +	Name      string `json:"name" yaml:"name"`
Comments needed here too.

2018-12-19 13:56 UTC, rossf7 commented on pkg/apis/application/v1alpha1/app_catalog_types.go
> +	// LogoURL contains the links for logo image file for this application catalog
Same here.

2018-12-19 13:56 UTC, rossf7 commented on pkg/apis/application/v1alpha1/app_catalog_types.go
> +	// Title is the name of the application catalog for this CR
Why the change to application?

2018-12-19 13:56 UTC, rossf7 commented on pkg/apis/application/v1alpha1/app_types.go
> +	// Release is the version of this application which we would like to use.
```suggestion
 	// Release is the version of the app that should be deployed.
```

2018-12-19 13:56 UTC, rossf7 commented on pkg/apis/application/v1alpha1/app_types.go
> +	// KubeConfig is the name of secret resource  which represent specific k8s cluster where the application could be deployed.
```suggestion
 	// KubeConfig is the kubeconfig that should be used to connect to the cluster when deploying the app.
```

The current comment is specific to using a secret. In the future there might be other configuration options.

2018-12-19 14:33 UTC, kopiczko commented on pkg/apis/application/v1alpha1/app_types.go
> +	// Release is the version of this application which we would like to use.
I edited this comment to remove leading space.

2018-12-19 15:20 UTC, tomahawk28 commented on pkg/apis/application/v1alpha1/app_types.go
> +	Secret AppSpecKubeConfigSecret `json:"secret" yaml:"secret"`
`Secret is the reference of secret object which contains clusters info and IDs` is fine?

2018-12-20 14:26 UTC, rossf7 reviewed
@tomahawk28 This is very close. A last round of feedback and then lets get this merged.

2018-12-20 14:37 UTC, tomahawk28 commented on pkg/apis/application/v1alpha1/app_catalog_types.go
> +// AppCatalog CR example as below.
So same as app CR? okay.

2018-12-20 14:43 UTC, rossf7 commented on pkg/apis/application/v1alpha1/app_catalog_types.go
> +// AppCatalog CR example as below.
Yes please remove the CR examples from both.

2018-12-20 14:49 UTC, rossf7 reviewed
Couple more changes.

2018-12-20 14:49 UTC, rossf7 commented on pkg/apis/application/v1alpha1/app_types.go
> +	Namespace string `json:"namespace" yaml:"namespace"`
Every field needs godoc. 

`// Namespace is the namespace of the secret containing the kubeconfig.`

2018-12-20 14:49 UTC, rossf7 commented on pkg/apis/application/v1alpha1/app_types.go
> +	App string `json:"app" yaml:"app"`
This should be `Status`. Godoc can be.

`// Status is the status of the deployed app.`

2018-12-20 14:52 UTC, tomahawk28 commented
@rossf7 What about `lastUpdated` should we need it? if then, which type it should be?

2018-12-20 14:55 UTC, rossf7 commented
@tomahawk28 Lets leave `lastUpdated` for now.  We can add it later when the status resource is implemented in app-operator.

2018-12-20 15:33 UTC, rossf7 approved these changes
LGTM

2018-12-20 15:36 UTC, rossf7 commented
I removed Tim's review since he is rebooting for Xmas. 

@kopiczko PTAL.

2018-12-20 15:46 UTC, kopiczko approved these changes
LGTM

2018-12-20 15:47 UTC, merged