use date-time instead of date for ReleaseCycle CR
giantswarm/apiextensions pull request #200
Opened 2019-02-07 17:34 UTC by TheoBrigitte

This PR solves an issue where an operator throw the following error when watching ReleaseCycle CR.

```
E0207 14:39:35.302146   31346 streamwatcher.go:109] Unable to decode an event from the watch stream: unable to decode watch event: v1alpha1.ReleaseCycle.Spec: v1alpha1.ReleaseCycleSpec.EnabledDate: DisabledDate: u
nmarshalerDecoder: parsing time ""2019-01-12"" as ""2006-01-02T15:04:05Z07:00"": cannot parse """ as "T", error found in #10 byte of ...|019-01-12","enabledD|..., bigger context ...|8c89a5c143ce"},"spec":{"disable
dDate":"2019-01-12","enabledDate":"2019-01-08","phase":"enabled","rel|...
```

This is due to the fact that by default `time` object are decoded using `time.RFC3339` in [`time.UnmarshalJSON`](https://golang.org/src/time/time.go?s=37288:37335#L1230) which is incompatible with the json-schema [date](http://json-schema.org/latest/json-schema-validation.html#rfc.section.7.3.1) format.

`time.RFC3339` expects : `2019-01-12T08:00:00Z`
json-schema `date` expects : `2019-01-12`

This PR changes the json-schema format to `date-time` which match `time.RFC3339` format.

2019-02-07 17:36 UTC, xh3b4sd approved these changes
That makes sense to me.

2019-02-08 08:12 UTC, tuommaki approved these changes

2019-02-08 11:31 UTC, kopiczko requested changes
I would like to keep `date` here. Time doesn't make sense for releases. We can have separate type with custom `UnmarshalJSON` for that.

2019-02-08 12:16 UTC, kopiczko commented
Here's the potential fix: https://github.com/giantswarm/apiextensions/pull/201

2019-02-11 09:03 UTC, closed without merging