Define schema for AppCatalog CRD
giantswarm/apiextensions pull request #263
Opened 2019-07-25 00:02 UTC by sslavic

Towards giantswarm/giantswarm#5407

2019-07-25 09:26 UTC, kopiczko commented on pkg/apis/application/v1alpha1/app_catalog_types.go
> +const appCatalogCRDJSON = `
Why not yaml?

2019-07-25 09:36 UTC, rossf7 requested changes
What I care about here is maintainability.  This JSON will be hard to maintain and is a step backwards from what we have now IMO.

I would like us to take a step back and just add the OpenAPI validation rules as YAML. That is what this issue is about. I agree that the Go structs for the rules are difficult to work with.

If we want to change how we manage CRDs that should be a separate issue and we should have consensus in sig-operator.

2019-07-25 09:42 UTC, kopiczko commented
I'm personally fine with defining whole CRD in the const. I'm even biased that this the way to go ATM. But choosing JSON as a format is controversial.

Having that in a separate issue/PR makes sense though.

2019-07-25 09:49 UTC, rossf7 commented
Yes my main point here is we should make smaller iterations and have consensus before making major changes. This started out as a SWH task to add some validation rules and has escalated a lot. 

I also don't think there is consensus on using JSON for this.

2019-07-25 10:55 UTC, sslavic commented on pkg/apis/application/v1alpha1/app_catalog_types.go
> +const appCatalogCRDJSON = `
There are no yaml tags in the types, only json.
More details on slack thread: https://gigantic.slack.com/archives/C2MS2VB37/p1564049998054900

2019-07-25 10:59 UTC, kopiczko commented on pkg/apis/application/v1alpha1/app_catalog_types.go
> +const appCatalogCRDJSON = `
Ack. Yes that is a problem to some degree. We'd probably have to unmarshal to `map[string]interface{}` then marshal to json and then unmarshal to struct.

2019-09-02 16:30 UTC, rossf7 commented
@sslavic I think this can be closed?

2019-09-03 07:51 UTC, sslavic commented
@rossf7 we discussed yesterday on Slack, options were
- to delete this PR/branch and created new one, or
- use this PR/branch, rebase it and overwrite the commit with new one that's aligned with chart CRD 

I'm fine with either, @tomahawk28 suggested he will chose latter (see https://gigantic.slack.com/archives/C76JX6YLQ/p1567415625013000?thread_ts=1567415386.011000&cid=C76JX6YLQ )

2019-09-03 07:58 UTC, rossf7 commented
@sslavic But I think the validation was added here? 😕 https://github.com/giantswarm/apiextensions/pull/280

@tomahawk28 Do you still need this PR?

2019-09-03 07:59 UTC, tomahawk28 commented
@sslavic @rossf7 Sorry, I started with another branch. We can remove this branch.

2019-09-03 08:00 UTC, closed without merging