added first sketch for ha masters spec
giantswarm/apiextensions pull request #321
Opened 2020-01-20 13:40 UTC by anvddriesch

Here we can work on the CR we are going to use for HA-Masters. 
Towards: https://github.com/giantswarm/giantswarm/issues/8273

2020-01-20 13:42 UTC, anvddriesch commented
@xh3b4sd @lachlanh I have sketched a CR to work on :) Let's iterate from here!

2020-01-20 13:51 UTC, xh3b4sd requested changes
Please also check the infrastructure types and the CRD Schema Validation. We need this here as well once we sorted the spec. Just FYI.

2020-01-20 13:51 UTC, xh3b4sd commented on pkg/apis/core/v1alpha1/g8s_control_plane_types.go
> +//	  group: core.giantswarm.io
We should maybe make this part of the infrastructure type. /cc @tuommaki WDYT?

2020-01-20 13:51 UTC, xh3b4sd commented on pkg/apis/core/v1alpha1/g8s_control_plane_types.go
> +//	    kind: G8sControlPlane
So the idea is we use this for all providers, right? Any argument against that? When we have some infrastructure reference this should be fine, which I do not see in the spec below. So we would need to reference our own e.g. AWS specific type for the control plane so that we can also propagate instance type information and the like.

2020-01-20 13:51 UTC, xh3b4sd commented on pkg/apis/core/v1alpha1/g8s_control_plane_types.go
> +	Replicas int32 `json:"replicas,omitempty"`
So this is the number of masters we would need to define. The `aws-operator` would not reconcile the `G8sControlPlane` type bit the provider specific one, which then would not contain information about the replicas. I think there is the "owner" reference thingy which we would need to make use of. So when the `aws-operator` sees the AWS specific CP CR it can fetch the `G8sControlPlane` and read the replicas.

2020-01-20 13:58 UTC, tuommaki commented on pkg/apis/core/v1alpha1/g8s_control_plane_types.go
> +//	  group: core.giantswarm.io
You mean the group should be infrastructure? Yes.
```suggestion
//	  group: infrastructure.giantswarm.io
```

2020-01-20 13:58 UTC, tuommaki commented on pkg/apis/core/v1alpha1/g8s_control_plane_types.go
> +//	    kind: G8sControlPlane
The current [kubeadm proposal type](https://github.com/kubernetes-sigs/cluster-api/blob/master/docs/proposals/20191017-kubeadm-based-control-plane.md#new-api-types) has `InfrastructureTemplate` as `corev1.ObjectReference` in it so that might make sense here as well.

2020-01-20 14:02 UTC, xh3b4sd commented on pkg/apis/core/v1alpha1/g8s_control_plane_types.go
> +//	    kind: G8sControlPlane
I think that is wrong and is likely to change. I would like to stick with the ref naming.

2020-01-20 14:23 UTC, anvddriesch commented
I changed the group to `infrastructure` here as suggested. I agree it fits. However, I'm not really sure what I should look at in terms of infrastructure types. Currently I do not see something with that name in the apiextensions.

2020-01-20 14:27 UTC, anvddriesch commented on pkg/apis/core/v1alpha1/g8s_control_plane_types.go
> +//	    kind: G8sControlPlane
If there is no argument against having the `g8sControlPlane` for all providers I think it would make sense. Otherwise we could use a "awsControlPlane" directly which somehow makes the infrastructure reference redundant.

2020-01-20 14:32 UTC, anvddriesch commented on pkg/apis/core/v1alpha1/g8s_control_plane_types.go
> +	Replicas int32 `json:"replicas,omitempty"`
Am I understanding it correctly that while `g8sControlPlane` CR (reconciled by `cluster-operator`) has the reference to the aws specific infrastructure CR "downwards", the aws specific infrastructure CR (reconciled by `aws-operator` ) can also have an "owner" reference "upwards"?

2020-01-20 15:46 UTC, xh3b4sd commented on pkg/apis/core/v1alpha1/g8s_control_plane_types.go
> +	Replicas int32 `json:"replicas,omitempty"`
When we look at our architecture it is not really hierarchical. There is no up or down I think. We have a network of processes in which each node (process) of the network interacts with peers. The owner reference is as you said a way to figure out which data object is referencing the data object you are looking at.

2020-01-20 15:47 UTC, xh3b4sd commented
Please move the files to the infrastructure specific group directory. It is still in core.

2020-01-20 15:55 UTC, anvddriesch commented
As I said above, I did not see something with the name "infrastructure" so I wasn't entirely sure where to move it. In that case I'm going to make a new directory?

2020-01-20 16:04 UTC, anvddriesch commented on pkg/apis/core/v1alpha1/g8s_control_plane_types.go
> +	Replicas int32 `json:"replicas,omitempty"`
Thank you for the explanation, you are right about the architecture. I also think it makes perfect sense to reference in both directions here.

2020-01-21 04:34 UTC, tuommaki reviewed
Regarding the infrastructure apigroup for this, Tim meant this directory: https://github.com/giantswarm/apiextensions/tree/master/pkg/apis/infrastructure/v1alpha2

2020-01-21 04:34 UTC, tuommaki commented on pkg/apis/core/v1alpha1/g8s_control_plane_types.go
> +//	    kind: G8sControlPlane
>  I would like to stick with the ref naming.

Do you mean you prefer `InfrastructureReference` instead of `InfrastructureTemplate`? I'm fine with both. At current state I'm not 100% sure which one will end up being more appropriate, but since the type is also reference, I'm perfectly fine with `InfrastructureRef` / `InfrastructureReference`.

> If there is no argument against having the g8sControlPlane for all providers I think it would make sense.

I think `G8sControlPlane` would be the correct way to go since there's infrastructure specific object reference also.

2020-01-21 08:24 UTC, xh3b4sd commented on pkg/apis/core/v1alpha1/g8s_control_plane_types.go
> +//	    kind: G8sControlPlane
+1 `InfrastructureRef`.

2020-01-21 14:20 UTC, xh3b4sd commented on pkg/apis/core/v1alpha1/g8s_control_plane_types.go
> +type G8sControlPlane struct {
Let's please have godoc for this and a YAML example like in the other types. Then we also want to show the usage of the `giantswarm.io/docs` annotation. See https://github.com/giantswarm/fmt/blob/master/kubernetes/annotations_and_labels.md#common-annotations.

2020-01-21 14:20 UTC, xh3b4sd commented on pkg/apis/core/v1alpha1/g8s_control_plane_types.go
> +	InfrastructureReference string `json:"infrastructureReference"`
```suggestion
	InfrastructureReference string `json:"infrastructureRef"`
```

2020-01-21 14:20 UTC, xh3b4sd commented on pkg/apis/core/v1alpha1/g8s_control_plane_types.go
> +	// InfrastructureReference is a required reference to provider-specific
```suggestion
	// InfrastructureRef is a required reference to provider-specific
```

2020-01-22 04:26 UTC, tuommaki commented on pkg/apis/infrastructure/v1alpha2/g8s_control_plane_types.go
> +	InfrastructureReference string `json:"infrastructureReference"`
```suggestion
	InfrastructureReference corev1.ObjectReference `json:"infrastructureReference"`
```
See https://godoc.org/k8s.io/kubernetes/pkg/apis/core#ObjectReference

2020-01-22 04:26 UTC, tuommaki commented on pkg/apis/infrastructure/v1alpha2/g8s_control_plane_types.go
> +// KubeadmControlPlaneStatus defines the observed state of G8sControlPlane.
```suggestion
// G8sControlPlaneStatus defines the observed state of G8sControlPlane.
```

2020-01-31 16:03 UTC, xh3b4sd commented
It looks like the version of the code-generator changed and with it some behaviour so some expected code is not generated. We need a better understanding of this and see which version of the code-generator we need to use in order to make that thing here fly.

2020-02-03 12:24 UTC, anvddriesch commented
I looked a little bit into the code generator problem but don't quite understand it yet. : (

2020-02-03 15:44 UTC, anvddriesch commented
@xh3b4sd Lach and I worked on the prototypes of `g8sControlPlane` and `awsControlPlane`
Take a look when you can. :)

2020-02-03 15:51 UTC, xh3b4sd requested changes
Please put a bit more love into the godoc. The YAMLs are a bit sloppy there.

2020-02-03 15:51 UTC, xh3b4sd commented on pkg/apis/infrastructure/v1alpha2/aws_control_plane_types.go
> +              type: string
We want to run masters in different AZs.

2020-02-03 15:51 UTC, xh3b4sd commented on pkg/apis/infrastructure/v1alpha2/aws_control_plane_types.go
> +//	     name: ????
That needs more love. Check the other godocs. We want version labels, docs annotations (probably not in the other godocs), and the name is not a label.

2020-02-03 15:51 UTC, xh3b4sd commented on pkg/apis/infrastructure/v1alpha2/aws_control_plane_types.go
> +    openAPIV3Schema:
We need to start to version this. Check https://kubernetes.io/docs/tasks/access-kubernetes-api/custom-resources/custom-resource-definition-versioning/.

2020-02-03 15:51 UTC, xh3b4sd commented on pkg/apis/infrastructure/v1alpha2/g8s_control_plane_types.go
> +  names:
This needs versioned schema validations as well.

2020-02-03 15:51 UTC, xh3b4sd commented on pkg/apis/infrastructure/v1alpha2/g8s_control_plane_types.go
> +//    readyReplicas: 3
What is the status difference between replicas and ready replicas?

2020-02-03 15:51 UTC, xh3b4sd commented on pkg/apis/infrastructure/v1alpha2/g8s_control_plane_types.go
> +//    //TODO LH infrastructureRef ?
Yes.

2020-02-03 16:07 UTC, xh3b4sd commented on pkg/apis/infrastructure/v1alpha2/g8s_control_plane_types.go
> +//    readyReplicas: 3
Ack, so far this distinction was never important and both of these where set equal.

2020-02-04 10:43 UTC, lachlanh commented on pkg/apis/infrastructure/v1alpha2/g8s_control_plane_types.go
> +  names:
have added the schema validation, please check.

2020-02-04 10:44 UTC, lachlanh commented on pkg/apis/infrastructure/v1alpha2/g8s_control_plane_types.go
> +  version: v1alpha1
is this the right version ? awscontrolplane looks like it is at v1alpha2 ? @xh3b4sd @anvddriesch

2020-02-04 11:00 UTC, xh3b4sd commented on pkg/apis/infrastructure/v1alpha2/g8s_control_plane_types.go
> +  version: v1alpha1
My thinking was to keep it aligned with the package path version. So it would be `v1alpha2`. But then when we introduce `v1alpha3` we would create a new package. I would assume we would not want to create a new CRD then, but use the one which is versioned, so we can make the conversions. @giantswarm/sig-operator any ideas?

2020-02-04 11:01 UTC, xh3b4sd commented on pkg/apis/infrastructure/v1alpha2/g8s_control_plane_types.go
> +                  type: string
AFAIK `uid` is set automatically. We should drop it here.

2020-02-04 11:02 UTC, xh3b4sd commented on pkg/apis/infrastructure/v1alpha2/g8s_control_plane_types.go
> +                fieldPath:
`fieldpath` is not used in our case AFAIK. Let's drop.

2020-02-04 11:02 UTC, xh3b4sd commented on pkg/apis/infrastructure/v1alpha2/g8s_control_plane_types.go
> +                resourceVersion:
We may not want to specify this. Shouldn't be validated IMO.

2020-02-04 12:59 UTC, anvddriesch commented on pkg/apis/infrastructure/v1alpha2/aws_control_plane_types.go
> +              type: string
good point! I changed that to an array- hopefully the syntax is correct.

2020-02-04 13:00 UTC, anvddriesch commented on pkg/apis/infrastructure/v1alpha2/aws_control_plane_types.go
> +//	     name: ????
I updated it. I am not sure how the docs example should look like, though. What would it be?

2020-02-04 13:01 UTC, anvddriesch commented on pkg/apis/infrastructure/v1alpha2/aws_control_plane_types.go
> +    openAPIV3Schema:
I tried to add the versioning as I understood it from the doc. I dropped the "validation" part since it seemed redundant. Is that correct?

2020-02-04 13:06 UTC, xh3b4sd commented on pkg/apis/infrastructure/v1alpha2/aws_control_plane_types.go
> +				    type: string
Check the multi line strings. I always have the same problem when working with these so I am not sure why we decided to do it that way at all. @giantswarm/sig-operator why though?

2020-02-04 13:06 UTC, xh3b4sd commented on pkg/apis/infrastructure/v1alpha2/aws_control_plane_types.go
> +//		   giantswarm.io/docs:
Indentation.

2020-02-04 13:06 UTC, xh3b4sd commented on pkg/apis/infrastructure/v1alpha2/aws_control_plane_types.go
> +//       availabilityZones: eu-central-1a
That should be a list. Or do we want to do some comma separated string magic?

2020-02-04 14:58 UTC, lachlanh commented on pkg/apis/infrastructure/v1alpha2/g8s_control_plane_types.go
> +//      apiVersion: v1apha2
@xh3b4sd does this look like what we would expect here ?

2020-02-04 15:03 UTC, xh3b4sd commented on pkg/apis/infrastructure/v1alpha2/g8s_control_plane_types.go
> +//      apiVersion: v1apha2
You can check the Node Pool clusters on the installations to see if this makes sense.

2020-02-05 14:53 UTC, xh3b4sd commented on pkg/apis/infrastructure/v1alpha2/aws_control_plane_types.go
> +//		   giantswarm.io/docs:
This is still not 100%.

2020-02-05 14:53 UTC, xh3b4sd commented on pkg/apis/infrastructure/v1alpha2/aws_control_plane_types.go
> +// TODO
Just for the record we iterate here as we are not sure yet what we will need. In worst case we just clean up later.

2020-02-05 14:53 UTC, xh3b4sd commented on pkg/apis/infrastructure/v1alpha2/g8s_control_plane_types.go
> +  name: g8sControlPlanes.core.giantswarm.io
```suggestion
  name: g8scontrolplanes.infrastructure.giantswarm.io
```

2020-02-05 14:53 UTC, xh3b4sd commented on pkg/apis/infrastructure/v1alpha2/g8s_control_plane_types.go
> +    plural: g8sControlPlanes
```suggestion
    plural: g8scontrolplanes
```

2020-02-05 14:53 UTC, xh3b4sd commented on pkg/apis/infrastructure/v1alpha2/g8s_control_plane_types.go
> +    singular: g8sControlPlane
```suggestion
    singular: g8scontrolplane
```

2020-02-05 14:53 UTC, xh3b4sd commented on pkg/apis/infrastructure/v1alpha2/g8s_control_plane_types.go
> +//      cluster-operator.giantswarm.io/version:0.17.0
```suggestion
//      cluster-operator.giantswarm.io/version: 0.17.0
```

2020-02-05 14:53 UTC, xh3b4sd commented on pkg/apis/infrastructure/v1alpha2/aws_control_plane_types.go
> +//	   metadata:
```suggestion
//	 metadata:
```

2020-02-05 14:53 UTC, xh3b4sd commented on pkg/apis/infrastructure/v1alpha2/aws_control_plane_types.go
> +//	   metadata:
We also miss the owner reference.

2020-02-06 10:17 UTC, merged