Generate CRDs using controller-tools
giantswarm/apiextensions pull request #409
Opened 2020-04-13 16:28 UTC by tfussell

## Checklist

- [ ] Consider SIG UX feedback.
- [ ] Update changelog in CHANGELOG.md.

2020-04-13 16:54 UTC, tfussell commented on docs/crd/application.giantswarm.io_app.yaml
> -apiVersion: apiextensions.k8s.io/v1beta1
`controller-gen` names CRD files like `<group>_<plural name>.yaml` so this file has been renamed `docs/crd/application.giantswarm.io_apps.yaml`.

2020-04-13 16:56 UTC, tfussell commented on docs/crd/application.giantswarm.io_appcatalogs.yaml
> +    controller-gen.kubebuilder.io/version: (devel)
It would be preferable to use a released binary of `controller-gen` somehow to avoid this label.

2020-04-13 16:57 UTC, tfussell commented on pkg/apis/application/v1alpha1/app_catalog_types.go
> -// This might look something like the following.
We don't need these comments now that we have full YAMLs for all CRDs.

2020-04-13 16:57 UTC, tfussell commented on scripts/gen.go
> +	_ "sigs.k8s.io/controller-tools/cmd/controller-gen"
Ensuring the correct version of `controller-gen` is tracked in `go.mod` using this fake import.

2020-04-13 16:58 UTC, tfussell commented on scripts/gen.sh
> +go run "$(go list -m -f '{{.Dir}}' sigs.k8s.io/controller-tools)"/cmd/controller-gen/main.go  \
This is the actual generating step.

2020-04-13 17:02 UTC, tfussell commented on docs/crd/release.giantswarm.io_releases.yaml
> +              description: 'State indicates the availability of the release: deprecated,
Validation was lost here. Needs to be restored using a `kubebuilder` comment.

2020-04-13 17:39 UTC, kopiczko commented on docs/crd/application.giantswarm.io_appcatalogs.yaml
> +    controller-gen.kubebuilder.io/version: (devel)
Can we maybe dockerize release version in some (separate or this one) repository? Maybe docker image already exists? then we can generate stuff with `docker run` and volume bindings.

2020-04-13 17:40 UTC, kopiczko reviewed
Awesome work man! It would be cool if we somehow could use those yaml directly to install them in CPs (I saw what you wrote in the description). Would be good to try to align with https://github.com/giantswarm/opsctl/pull/596.

2020-04-13 19:21 UTC, xh3b4sd reviewed
I think this is a step into the right direction. Really cool. But we need to figure out how to extend the CRDs based on the CR related go types/comments. With this approach it would then maybe make sense to simply download the YAML files in `opsctl` in order to ensure them.

2020-04-13 19:21 UTC, xh3b4sd commented on docs/crd/infrastructure.giantswarm.io_awsmachinedeployments.yaml
> +                  type: object
Here is the defaulting missing now. How can this be generated?

2020-04-13 19:21 UTC, xh3b4sd commented on scripts/gen.go
> +	_ "sigs.k8s.io/controller-tools/cmd/controller-gen"
When this is how we want to keep it we need some useful comment in here to explain how this works and why this is necessary to be like that.

2020-04-13 20:30 UTC, tfussell commented on docs/crd/infrastructure.giantswarm.io_awsmachinedeployments.yaml
> +                  type: object
I added this defaulting back for this type. Check it out https://github.com/giantswarm/apiextensions/blob/13a6fe276127e87caceb26cbe44a431e286aa51d/docs/crd/infrastructure.giantswarm.io_awsmachinedeployments.yaml#L74-L82 There's a learning curve, but it feels pretty intuitive once you get going. I can cross-check generated CRDs against existing validation tomorrow to make sure we don't change any semantics accidentally.

2020-04-13 20:34 UTC, tfussell commented on scripts/gen.go
> +	_ "sigs.k8s.io/controller-tools/cmd/controller-gen"
I agree. I got this pattern from somewhere. I will document it unless we end up changing the method using docker or something.

2020-04-13 20:36 UTC, tfussell commented on pkg/apis/provider/v1alpha1/kvm_types.go
> -	Disk               float64 `json:"disk" yaml:"disk"`
According to https://github.com/kubernetes-sigs/controller-tools/issues/245#issuecomment-518465214, `float64` is not a good type to use in Kubernetes due to round-tripping issues. I'm not sure what the implications of changing this type would be though.

2020-04-14 08:04 UTC, marians commented on docs/crd/core.giantswarm.io_certconfigs.yaml
> +status:
I am missing all the property descriptions here from https://github.com/giantswarm/apiextensions/blob/master/pkg/apis/core/v1alpha1/cert_types.go#L36-L100 :-(

2020-04-14 08:12 UTC, marians commented
Property descriptions apparently are now coming from Go comments. This has several ramifications:

1. All the descriptions from our YAML schema are missing. For an example, look at CertConfig.

2. There is a mix between Go and JSON/YAML casing, as the description always repeats the Go name of the field as a first word. Example: 

```yaml
  properties:
    configMap:
      description: ConfigMap references a config map containing catalog
        values that should be applied to apps in this catalog.
```

From a UX perspective, that's less than ideal.

3. Also not ideal in terms of readability is that the descriptions are repeating the field name.

I see the benefit of having descriptions only in one place. However, using the Golang one is a trade-off for where UX loses.

2020-04-14 08:14 UTC, marians requested changes
As it is this PR means we are loosing descriptions.

2020-04-14 08:33 UTC, xh3b4sd commented
Let's not mix docs with internal tooling. In this PR the docs are actually overwritten which we could change. It may not be reasonable to try to solve our documentation needs in one solution together with our internal CRD management. So separating this would probably be better.

2020-04-14 09:32 UTC, kopiczko commented
> Let's not mix docs with internal tooling. In this PR the docs are actually overwritten which we could change. It may not be reasonable to try to solve our documentation needs in one solution together with our internal CRD management. So separating this would probably be better.

I don't get that. Can you elaborate here? Or maybe tell what you are referring to?

2020-04-14 09:35 UTC, kopiczko commented
> I see the benefit of having descriptions only in one place. However, using the Golang one is a trade-off for where UX loses.

Is the lost bigger than the benefit in your opinion? I'd say people who read those are kind of used to Go style comments. For me not copying stuff over and having simpler workflows by far outweighs a problem of description starting with a repeated name.

2020-04-14 09:56 UTC, xh3b4sd commented
Marian and Thomas started to generate CRDs for documentation reasons and put them in the `docs/` folder. This is what is used to display in https://docs.giantswarm.io/reference/cp-k8s-api. Thomas now wanted to generate the CRDs we use with our tooling instead of having these multi line string definitions in go variables. His result as per this pull request is written to the `docs/` folder, which now mixes two different purposes. I was questioning if it is good to mix these two use cases which both have likely totally different requirements. So maybe we want to thrive for one approach to rule them all but maybe this is more complicated than necessary. Just wanted to nudge on that a bit.

2020-04-14 09:57 UTC, xh3b4sd commented
> For me not copying stuff over and having simpler workflows by far outweighs a problem of description starting with a repeated name.

Which is you, the developer speaking. Marian thinks about the users. See my comment about mixing use cases above.

2020-04-14 10:08 UTC, marians commented
@xh3b4sd Everything in the `docs/` folder is generated automatically. The CRD content with all the schema property `description` texts is contained in YAML strings in Go code. [Example](https://github.com/giantswarm/apiextensions/blob/master/pkg/apis/core/v1alpha1/cert_types.go#L36-L100)

The problem is not that we overwrite `docs/`. The problem is that we

- have some descriptions in there coming from Go code. This means the outcome is a little strange for end users (but probably still usable).
- lose descriptions which are currently present only in YAML. This means we have to at least make sure we transfer the descriptions from the YAML strings to Go comments before re-generating the `docs` content.

2020-04-14 10:11 UTC, marians commented
@kopiczko 
> Is the lost bigger than the benefit in your opinion?

That's hard to judge and to compare, mainly as the gains and losses happen on different ends (internal vs. external).

I think most users will be able to cope with the strangeness and still be able to make the right conclusions. If this helps us getting more complete, up-to-date and accurate property docs, fine. I'm not in the way.

2020-04-14 14:13 UTC, tfussell commented
Thanks for the review and comments. I'll try to address each concern.

2020-04-14 14:17 UTC, tfussell commented on docs/crd/core.giantswarm.io_certconfigs.yaml
> +status:
Sorry, didn't want to erase your hard work. I will copy and paste them into CR field comments so they make it back into the CRD before I merge. I didn't want to invest the time initially if it seemed like a bad approach in general.

2020-04-14 14:38 UTC, tfussell commented
> > For me not copying stuff over and having simpler workflows by far outweighs a problem of description starting with a repeated name.
> 
> Which is you, the developer speaking. Marian thinks about the users. See my comment about mixing use cases above.

I think we have the opportunity to address both use cases with this change. Here's how:
- As you know, with the old method, we had multiline strings in source code containing manually defined CRDs. These CRDs were unmarshalled into `runtime.Object`s and then marshalled back into standalone YAML files in the `docs/crd` directory using bespoke tooling. Aligning with upstream Kubernetes means our libraries are more easily understood by internal developers and external technical users.
- The old method required us to write CRDs by hand without syntax highlighting or validation because they were YAML documents in Go source which provided many opportunities for mistakes or outdated schemata/documentation. By generating CRDs from CR structs, we know that our CRDs are valid Kubernetes objects and that they are in sync with CRs.
- We now have a CRD with a schema [for every type](https://github.com/giantswarm/apiextensions/tree/generate-crds/docs/crd) "for free" which means more documentation and validation for computers and humans even if it's computer generated. It also gives us the ability to move to `v1` `CustomResourceDefinition` which does not allow disabling pruning.
- When we add GoDoc comments to our CR fields, we get them in the CRD field descriptions automatically. This means improving DX (developer experience) also improves UX and vice versa.

2020-04-14 15:22 UTC, xh3b4sd reviewed
This is cool. We discussed a little. Here are some final thoughts. 

* When the go types changed, but the CRDs are not re-generated, CI should fail in an idea world. Not a big deal in the first step, but let's consider this for the upcoming PRs. 
* I already made the experience that the files are hard to determine in the Github file tree UI because the generated file names are super long. This makes it super hard for humans to identify where the file you are looking for is. Maybe we could work more with a directory structure. Just an idea. 
* It is amazing that now all CR status structures are also defined and that the whole schemas are actually structural and valid. This makes so much sense. 
* We should test this somehow on a Control Plane to see if the CRDs are still fine. We can maybe talk about it and try something out together. It is a bit dangerous to deal with so we should make sure this does not break production environments.

2020-04-14 15:22 UTC, xh3b4sd commented on docs/crd/infrastructure.giantswarm.io_awsmachinedeployments.yaml
> +                      type: integer
In `master` there is also `format: int32`. I am not sure how relevant this is. Just found the difference.

2020-04-14 15:22 UTC, xh3b4sd commented on docs/crd/infrastructure.giantswarm.io_awsmachinedeployments.yaml
> +    storage: true
With this now how does it work to add a new version? I thought the whole schema should be in that list but instead I see that the schema is defined at the top level `spec.validation`. I would actually like to put everything into `spec.versions` since I understood this is how to define multiple ones. It is further unclear to me how the CR has to be defined to make that change effective in the generated CRD.

2020-04-14 16:05 UTC, tfussell commented on docs/crd/infrastructure.giantswarm.io_awsmachinedeployments.yaml
> +    storage: true
I've done some research on this, and this is an important difference between `v1beta1.CustomResourceDefinition` and `v1.CustomResourceDefinition`. In `v1beta1`, you must either:
- Define validation at the top level `.spec.validation`.
- OR Have multiple versions with different `.schema` fields.
When we ran into this a few months ago, we got around it by defining a dummy unused version which had a null schema thereby satisfying the second requirement. This generator takes the first approach and defines a top level validation.

In `v1`, the top level fields are removed so it's naturally allowed to have a single version with a schema.

These issues might not become apparent until we actually try to create the CRDs on a running Kubernetes API so it's important that we actually create them during testing I think.

2020-04-14 16:10 UTC, xh3b4sd commented on docs/crd/infrastructure.giantswarm.io_awsmachinedeployments.yaml
> +    storage: true
Then let's already graduate the `AWSMachineDeployment` CRD to `apiextensions/v1` and test that.

2020-04-14 16:11 UTC, tfussell commented on docs/crd/application.giantswarm.io_appcatalogs.yaml
> +    controller-gen.kubebuilder.io/version: (devel)
This would be nice, but I tend to worry about the added complexity of keeping another image updated. What do you think about the `cluster-api` approach of installing the tool before build? https://github.com/kubernetes-sigs/cluster-api/blob/master/Makefile#L164-L165 In this case it's using a `Makefile`, but I guess we can just add it to `scripts/gen.sh`.

2020-04-14 18:51 UTC, tfussell commented on docs/crd/infrastructure.giantswarm.io_awsmachinedeployments.yaml
> +    storage: true
I've made some significant improvements to the scripts directory and upgraded all CRDs to `v1`. Feel free to test them.

2020-04-14 18:54 UTC, xh3b4sd commented on docs/crd/infrastructure.giantswarm.io_awsmachinedeployments.yaml
> +    storage: true
We only need to graduate `AWSMachineDeployment` for now. At least that was what we agreed on with Firecracker, Marcel and Timo when we talked earlier. Reason was to keep the friction down since we did not know what breaks when we roll out all at once the new way. So unless you are super confident this is the right move we should only do it with `AWSMachineDeployment` because this is necessary due to our wish to use defaulting. All others are not so super important and we can sort them in further iterations.

2020-04-14 19:15 UTC, kopiczko commented
Another thought which I don't know why I didn't propose in the first place. I'd be fine with breaking godoc conventions for there files to have CRDs properly generated. We can add `// nolint:godoc` (don't know if this is godoc or something else) for those files and treat them exceptionally.

2020-04-14 19:15 UTC, tfussell commented on docs/crd/infrastructure.giantswarm.io_awsmachinedeployments.yaml
> +    storage: true
Would it be alright to do all of `infrastructure.giantswarm.io`? There's not an easy way to select individual types, but I can select a package with the upstream tools.

2020-04-14 19:16 UTC, tfussell commented on docs/crd/infrastructure.giantswarm.io_awsmachinedeployments.yaml
> +    storage: true
All of the other groups have been reverted to `v1beta1`.

2020-04-14 19:19 UTC, xh3b4sd commented on docs/crd/infrastructure.giantswarm.io_awsmachinedeployments.yaml
> +    storage: true
Works for me when we automate the migration and test that. Should be fine since the proper schemas are generated.

2020-04-14 19:44 UTC, marians commented on docs/crd/core.giantswarm.io_certconfigs.yaml
> +status:
Sure, I understand.

2020-04-15 03:11 UTC, tfussell commented
> Another thought which I don't know why I didn't propose in the first place. I'd be fine with breaking godoc conventions for there files to have CRDs properly generated. We can add `// nolint:godoc` (don't know if this is godoc or something else) for those files and treat them exceptionally.

I checked cluster-api and it uses normal GoDoc style comments for CRs (field name in CamelCase at the beginning of each one). Both ways seem reasonable to me.

2020-04-15 08:14 UTC, marians commented
Anyway, I'd leave the comment changes out of this PR. We can tackle that later.

2020-04-16 03:29 UTC, tfussell commented on docs/crd/application.giantswarm.io_appcatalogs.yaml
> +    controller-gen.kubebuilder.io/version: (devel)
This is improved in the following PR (#410) so I'm not too worried about this being perfect.

2020-04-16 03:29 UTC, tfussell commented on scripts/gen.go
> +	_ "sigs.k8s.io/controller-tools/cmd/controller-gen"
Resolved in #410

2020-04-16 03:35 UTC, tfussell commented
This PR isn't perfect, but most of the issues are resolved in the next PR, #410. If it's okay with everyone, I would merge this to master after some approvals and tie up any loose ends in the next PR.

2020-04-16 03:36 UTC, tfussell commented
The only remaining task for this PR is figuring out what to do about the `float64` fields. I will work on that tomorrow. Open to ideas.

2020-04-16 07:24 UTC, xh3b4sd commented
I did not fully understand the problem and we can talk about it in more detail if you like. I just found `kubebuilder:validation:Type` which may help to enforce the right type?

2020-04-16 13:01 UTC, tfussell commented on pkg/apis/core/v1alpha1/kvm_cluster_types.go
> +	// +kubebuilder:validation:Type=number
Specifying the type here for validation. This will still be a breaking change for the `kvm-operator` but should be able to work around it with `strconv.ParseFloat(MemorySizeGB, 64)`. I'll test in `kvm-operator` now.

2020-04-16 14:15 UTC, tfussell commented
Now that `float64` has been fixed, this PR has been effectively subsumed by https://github.com/giantswarm/apiextensions/pull/410 so I'm going to merge it and continue work in the next PR with an announcement that `apiextensions@master` is a WIP.

2020-04-16 17:45 UTC, xh3b4sd commented
Closing in favour of https://github.com/giantswarm/apiextensions/pull/410.

2020-04-16 17:45 UTC, closed without merging