Add subnet and metadata annotations
giantswarm/apiextensions pull request #603
Opened 2020-10-30 11:07 UTC by paurosello

## Checklist

- [ ] Consider SIG UX feedback.
- [ ] Update changelog in CHANGELOG.md.
- [ ] If adding a new type, ensure that it is added to the [CRD unit tests](https://github.com/giantswarm/apiextensions/blob/d78aba91d578d56ef49f58e336035d35edc4e1b0/pkg/crd/crd_test.go#L9).

2020-10-30 11:40 UTC, calvix approved these changes

2020-10-30 12:08 UTC, xh3b4sd approved these changes

2020-10-30 12:13 UTC, pipo02mix approved these changes
LGTM nice

2020-10-30 12:33 UTC, marians requested changes

2020-10-30 12:33 UTC, marians commented on pkg/annotation/aws.go
> +const AWSMetadataV2 = "alpha.aws.giantswarm.io/metadata-v2"
I don't understand the description completely.

> The value can be either optional or required.

Does that mean it can be either the string`"optional"` or `"required"`? If yes, please set the values in quotes.

The docs link points to a setting named `HttpEndpoint` which allows the value `disabled` or `enabled`. I don't understand how this explains the meaning of this annotation.

Should that link point to `HttpTokens` instead? Then please use the URL https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-ec2-launchtemplate-launchtemplatedata-metadataoptions.html#cfn-ec2-launchtemplate-launchtemplatedata-metadataoptions-httptokens

2020-11-03 08:26 UTC, paurosello commented on pkg/annotation/aws.go
> +const AWSMetadataV2 = "alpha.aws.giantswarm.io/metadata-v2"
Yep, could get the URL correctly previously but that looks better, thanks for pointing out

2020-11-03 08:44 UTC, marians commented on pkg/annotation/aws.go
> +// the state of token usage for your instance metadata requests.
I still don't understand this sentence:

> AWSMetadataV2 is the aws update annotation used for configuring the state of token usage for your instance metadata requests.

Maybe just copy and adapt the entire description from upstream? Lines are for free.

```suggestion
// AWSMetadataV2 configures token usage for your instance metadata requests.
// If the value is 'optional', you can choose to retrieve instance metadata with or without a signed token
// header on your request. If you retrieve the IAM role credentials without a token, the version 1.0 role
// credentials are returned. If you retrieve the IAM role credentials using a valid signed token, the version
// 2.0 role credentials are returned.
// If the state is 'required', you must send a signed token header with any instance metadata retrieval
// requests. In this state, retrieving the IAM role credentials always returns the version 2.0 credentials; the
// version 1.0 credentials are not available.
// Default: 'optional'
```

2020-11-03 08:45 UTC, marians commented on pkg/annotation/aws.go
> +// The value can be either "optional" or "required". Default is "optional".
With my suggestion above, line 18 can be dropped.

2020-11-03 08:54 UTC, merged

2020-11-03 09:24 UTC, marians commented on pkg/annotation/aws.go
>  // The value can be either "optional" or "required". Default is "optional".
As I wrote, this line is redundant now

2020-11-03 09:30 UTC, paurosello commented on pkg/annotation/aws.go
>  // The value can be either "optional" or "required". Default is "optional".
yes, it was removed

2020-11-03 09:37 UTC, marians commented on pkg/annotation/aws.go
>  // The value can be either "optional" or "required". Default is "optional".
Thanks! I looked at an outdated diff without noticing.